#!/usr/bin/env bash
#### moonraker-timelapse module
####
#### https://github.com/mainsail-crew/moonraker-timelapse
#### Thanks to Fry Sennberg for this bueatiful "Plugin"
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2022
#### https://github.com/mainsail-crew/MainsailOS
####
#### This File is distributed under GPLv3
####

###### THIS MODULE HAS TO BE PLACED RIGHT AFTER "moonraker" MODULE!!!

# shellcheck enable=require-variable-braces

## Source error handling, leave this in place
set -Eex

## Set LC_ALL to prevent errors
export LC_ALL=C

# Set DEBIAN_FRONTEND to noninteractive
if [[ "${DEBIAN_FRONTEND}" != "noninteractive" ]]; then
    export DEBIAN_FRONTEND=noninteractive
fi

## Source CustomPIOS common.sh
# shellcheck source=/dev/null
source /common.sh

install_cleanup_trap

run_as_base() {
    local base_home="/home/${BASE_USER}"
    if command -v runuser >/dev/null 2>&1; then
        runuser -u "${BASE_USER}" -- env HOME="${base_home}" USER="${BASE_USER}" LOGNAME="${BASE_USER}" PATH="$PATH" "$@"
    else
        HOME="${base_home}" USER="${BASE_USER}" LOGNAME="${BASE_USER}" sudo -u "${BASE_USER}" "$@"
    fi
}

## helper func moonraker update_manager
add_timelapse_entry() {
    if [[ -f "${TIMELAPSE_CONFIG_DIR}/moonraker.conf" ]]; then
        if [[ -f "/tmp/moonraker.conf" ]]; then
            rm -rf /tmp/moonraker.conf
        fi
        run_as_base bash -c "cat '${TIMELAPSE_CONFIG_DIR}/moonraker.conf' '${TIMELAPSE_TEMPLATE}' > /tmp/moonraker.conf"
        install -o "${BASE_USER}" -g "${BASE_USER}" -m 0644 /tmp/moonraker.conf "${TIMELAPSE_CONFIG_DIR}/moonraker.conf"
    fi
    ## Cleanup template
    if [[ -f "${TIMELAPSE_TEMPLATE}" ]]; then
        rm -f "${TIMELAPSE_TEMPLATE}"
    fi
}

echo_green "Installing moonraker-timelapse plugin ..."

### Install template file
# unpack /filesystem/home/${BASE_USER} /home/${BASE_USER} ${BASE_USER}

## Install all deps at once for time consumption reasons.
## APT: Update Repo Database and install Dependencies
# Force apt update
apt-get update
echo_green "Installing moonraker-timelapse Dependencies ..."
## Disabling shellcheck SC2086, because we want "wordsplitting"
# shellcheck disable=SC2086
check_install_pkgs ${TIMELAPSE_DEPS}


## Clone klipper repo
pushd "/home/${BASE_USER}" &> /dev/null || exit 1
if [[ -d "/home/${BASE_USER}/moonraker-timelapse/.git" ]]; then
    echo_green "Updating existing repo /home/${BASE_USER}/moonraker-timelapse"
    run_as_base git -C "/home/${BASE_USER}/moonraker-timelapse" fetch --all --prune || true
    if [[ -n "${TIMELAPSE_REPO_BRANCH:-}" ]]; then
        run_as_base git -C "/home/${BASE_USER}/moonraker-timelapse" checkout "${TIMELAPSE_REPO_BRANCH}" || run_as_base git -C "/home/${BASE_USER}/moonraker-timelapse" checkout -B "${TIMELAPSE_REPO_BRANCH}"
        run_as_base git -C "/home/${BASE_USER}/moonraker-timelapse" reset --hard "origin/${TIMELAPSE_REPO_BRANCH}" || true
    else
        run_as_base git -C "/home/${BASE_USER}/moonraker-timelapse" pull --ff-only || true
    fi
    if [[ -n "${TIMELAPSE_REPO_SHIP:-}" ]]; then
        run_as_base git -C "/home/${BASE_USER}/moonraker-timelapse" remote set-url origin "${TIMELAPSE_REPO_SHIP}" || true
    fi
else
    gitclone TIMELAPSE_REPO moonraker-timelapse
fi
chown -R "${BASE_USER}:${BASE_USER}" "/home/${BASE_USER}/moonraker-timelapse"

## Link component
if [[ -d "${TIMELAPSE_PYTHON_VENV_DIR}" ]]; then
    run_as_base ratos extensions register moonraker "timelapse" "${TIMELAPSE_SRC_DIR}/component/timelapse.py"
fi

## Link timelapse.cfg
if [[ -d "${TIMELAPSE_CONFIG_DIR}" ]]; then
    echo "Linking macro file ..."
    run_as_base ln -sf "${TIMELAPSE_SRC_DIR}/klipper_macro/timelapse.cfg" "${TIMELAPSE_CONFIG_DIR}/timelapse.cfg"
fi

## Extend moonraker.conf
# echo "Modifying moonraker.conf ..."
# add_timelapse_entry

popd &> /dev/null || exit 1

## Done message
echo_green "Installing moonraker-timelapse plugin ... done!"
