name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: New version number in X.Y.Z
        required: true

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
    steps:
      - name: "📥 Checkout"
        uses: actions/checkout@v4
        with:
          ref: v2.1.x
          fetch-depth: 0

      - name: "🔎 Check release number"
        run: |
          VERSION="${{ github.event.inputs.version }}"
          if ! [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$ ]]; then
            echo "::error::Version '$VERSION' is not SemVer compliant. Required format: X.Y.Z or X.Y.Z-alpha.N"
            exit 1
          fi

      - name: "Get latest tag"
        id: latest_tag
        shell: bash
        run: |
          echo "TAG_NAME=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_OUTPUT

      - name: "Setup git config"
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: "Update VERSION file"
        run: |
          echo "${{ github.event.inputs.version }}" > ./src/version
          git add ./src/version
          git commit -m "chore: bump version to v${{ github.event.inputs.version }}"
          git push

      - name: "Push tag"
        run: |
          git tag -a ${{ github.event.inputs.version }} -m "${{ github.event.inputs.version }}"
          git push origin ${{ github.event.inputs.version }}

      - name: "Generate a changelog"
        uses: orhun/git-cliff-action@v4
        id: changelog
        with:
          config: cliff-release.toml
          args: ${{ steps.latest_tag.outputs.TAG_NAME }}..HEAD

      - name: "Create Release"
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: RatOS ${{ github.event.inputs.version }}
          body: ${{ steps.changelog.outputs.content }}
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

  finish-release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: "Publish Release"
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh release edit "${{ github.event.inputs.version }}" --draft=false

  generate-matrix:
    name: Create Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: v2.1.x

      - name: Create Matrix
        id: create-matrix
        shell: python
        run: |
          PY_INT=$(command -v python3)
          CONFIG="${{ github.workspace }}/.github/workflow_config.yml"
          GROUP="release"
          $PY_INT ${{ github.workspace }}/.github/scripts/setup_matrix.py -c $CONFIG -g $GROUP --git

  build:
    needs: [prepare-release, generate-matrix]
    runs-on: ubuntu-latest
    outputs:
      base_name: ${{ steps.move-image.outputs.base_name }}
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Cache aptitude
        uses: actions/cache@v2
        with:
          path: repository/src/workspace/aptcache
          key: ${{ runner.os }}-apt-get-${{ hashFiles('**/apt.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-get-

      - name: Build image
        id: build
        uses: mainsail-crew/MainsailOS-actions/build-image@master
        with:
          config: ${{ matrix.config }}
          build-ref: v2.1.x
          custompios-ref: 1.5.0

      - name: Upload failed Logfile
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failed-${{ steps.move-image.outputs.image }}.log
          path: repository/src/build.log

      - name: Rename image file
        id: move-image
        shell: bash
        run: |
          WORKSPACE=$(echo ${{ github.workspace }})
          sudo chown -R $USER:$USER $WORKSPACE/repository/src/workspace || true
          sudo chmod 0775 -R $WORKSPACE/repository/src/workspace || true

          source repository/src/config
          base_name="${{ needs.prepare-release.outputs.release_id }}-${DIST_NAME}-${DIST_VERSION}"
          image="${base_name}-${{ steps.build.outputs.type }}-${{ steps.build.outputs.sbc }}"
          mv repository/src/workspace/*.img $image.img

          echo "base_name=${base_name}" >> $GITHUB_OUTPUT
          echo "image=${image}" >> $GITHUB_OUTPUT

      - name: Compressing Image
        shell: bash
        run: |
          CPU_COUNT="$(nproc)"
          echo -e "\e[32mUsing ${CPU_COUNT} Cores for compression...\e[0m"
          xz -efkvz9T"${CPU_COUNT}" ${{ steps.move-image.outputs.image }}.img || true

      # Todo: use gh release with artifacts
      # Todo: calculate checksums?
      # Todo: calculate filesizes?
      # Todo: generate JSON metadata?
